### ISSUE TITLE
update contributing guide 

### ISSUE THREAD

**Issue by hspitzer** [theislab/squidpy_notebooks#69]
Quick reminder to integrate stuff discussed in #64  to contributing guide (how docs are regenerated, manual update of examples.rst in main repo)

**Comment by michalk8** [comment]
I think most has been added there in #64 , except maybe for `examples.rst` update. Regarding this we can also when generating the docs in main repo, copy `examples.rst`, `tutorials.rst` and `references.{bib,rst}` and use those (easy to do, maybe more convoluted).
Unrelated to above, I'd suggest adding default glob to both `{examples,tutorials}.rst` so that missing examples as mentioned in https://github.com/theislab/squidpy/issues/366#issuecomment-862503505 don't happen (I'd rather have then all up, even if the order is sub-optimal).

**Comment by michalk8** [comment]
@hspitzer I believe this can be closed once #74 (added 1 sentence on where to add examples/tutorials); also please ignore the `glob` for `examples/tutorials`, since they are files from diff. directories are in different sections.

**Comment by hspitzer** [comment]
yes, sounds good!

> Unrelated to above, I'd suggest adding default glob to both {examples,tutorials}.rst so that missing examples as mentioned > in heislab/squidpy#366 (comment) don't happen (I'd rather have then all up, even if the order is sub-optimal).

you mean ignore this comment? Ok!

**Comment by michalk8** [comment]
> you mean ignore this comment? Ok!

Yes, thanks.

closed via #74
